version: 2.1

parameters:
  pipeline-batch1:
    description: "Switch to true to trigger the pipeline for the batch1"
    type: boolean
    default: true # パイプラインを実行する場合は、trueを設定
  # pipeline-batch2:
  #   description: "Switch to true to trigger the pipeline for the batch2"
  #   type: boolean
  #   default: false # パイプラインを実行する場合は、trueを設定

executors:
  temurin:
    docker:
      - image: ${DEVELOPMENT_TOOL_GCP_REGION}-docker.pkg.dev/${DEVELOPMENT_TOOL_GCP_PROJECT}/${DEVELOPMENT_TOOL_BASE_AR_REPO_NAME}/maven:3.9.9-eclipse-temurin-21
        auth:
          username: _json_key
          password: ${DEVELOPMENT_TOOL_GSA_KEY}
  google-cloud-cli:
    docker:
      - image: gcr.io/google.com/cloudsdktool/google-cloud-cli:slim

commands:

  unit_test:
    steps:
      - run:
          name: Run tests
          command: mvn -f ./pom.xml clean verify -s ./settings.xml
  
  scan_sbom:
    steps:
      - run:
          name: Install Syft
          command: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Make SBOM
          command: |
            syft scan . \
              --source-name $(basename $(pwd)) \
              --source-version $(echo $(git rev-parse --abbrev-ref HEAD))
      - run:
          name: Install Grype
          command: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Analyze SBOM
          command: grype sbom:./target/syft-sbom.json
  
  analyze_dependency:
    steps:
      - run:
          name: Analyze maven dependencies
          command: |
            mvn -f ./pom.xml dependency-check:check -s ./settings.xml

  check_coding_bug:
    steps:
      - run:
          name: Check coding bugs
          command: mvn -f ./pom.xml spotbugs:check -s ./settings.xml

  store_static_analyzed_reports:
    steps:
      - store_artifacts:
          path: ./target/dependency-check-report.json
          destination: dependency-check-report.json
      - store_artifacts:
          path: ./target/dependency-check-report.html
          destination: dependency-check-report.html
      - store_artifacts:
          path: ./target/spotbugsXml.xml
          destination: spotbugsXml.xml
      - store_artifacts:
          path: ./target/spotbugs.html
          destination: spotbugs.html
      - store_artifacts:
          path: ./target/syft-sbom.json
          destination: syft-sbom.json
      - store_artifacts:
          path: ./grype-scan-report.json
          destination: grype-scan-report.json

  store_unit_test_reports:
    steps:
      - store_artifacts:
          path: ./target/site/jacoco
          destination: jacoco

  gcloud_setting:
    steps:
      - run:
          name: Authorize Google Cloud for Image Push and Deploy
          command: |
            echo ${BATCH_GSA_KEY} | gcloud auth activate-service-account --key-file=-
            gcloud auth list
            gcloud config list

  deploy:
    steps:
      - run:
          name: Deploy to HTTP Function
          command: |
            gcloud functions deploy ${BATCH_NAME} \
              --gen2 \
              --project=${BATCH_GCP_PROJECT} \
              --region=${BATCH_GCP_REGION} \
              --runtime=${BATCH_RUNTIME} \
              --source=./ \
              --entry-point=${BATCH_ENTRY_POINT} \
              --trigger-http \
              --allow-unauthenticated

jobs:
  batch1-static-analysis:
    executor: temurin
    working_directory: ~/project/batches/batch1
    steps:
      - checkout:
          path: ~/project
      # - restore_cache:
      #     keys:
      #       - dependency-check-db-{{ .Branch }}-{{ .Revision }}
      #       - dependency-check-db-
      - scan_sbom
      # - analyze_dependency
      - check_coding_bug
      # - save_cache:
      #     paths:
      #       - .m2/repository/org/owasp/dependency-check-data
      #     key: dependency-check-db-{{ .Branch }}-{{ .Revision }}
      - store_static_analyzed_reports
  
  batch1-unit-test:
    executor: temurin
    working_directory: ~/project/batches/batch1
    steps:
      - checkout:
          path: ~/project
      - unit_test
      - store_unit_test_reports

  batch1-deploy:
    executor: google-cloud-cli
    working_directory: ~/project/batches/batch1
    steps:
      - checkout:
          path: ~/project
      - gcloud_setting
      - deploy


workflows:

  batch1-develop:
    when: 
      and: 
        - equal: [ true, << pipeline.parameters.pipeline-batch1 >> ]
        - or: 
          - equal: [ "main", << pipeline.git.branch >> ] # 一時的にdevelopからmainに変更
          - matches: { pattern: "^feature/.*", value: << pipeline.git.branch >> }
          - matches: { pattern: "^bugfix/.*", value: << pipeline.git.branch >> }
    jobs:
      # プレビルドパイプライン
      - batch1-static-analysis:
          filters: &prebuild_filters
            branches:
              only: 
                - /^feature\/.*|^bugfix\/.*/
                - main # 一時的にdevelopからmainに変更
          context:
            - DEVELOPMENT_TOOL
            - BATCH1_DEV
      - batch1-unit-test:
          filters: *prebuild_filters
          context:
            - DEVELOPMENT_TOOL
            - BATCH1_DEV
      # デプロイパイプライン
      - batch1-deploy:
          requires:
            - batch1-static-analysis
            - batch1-unit-test
          filters: &develop_filters
            branches:
              only: 
                - main # 一時的にdevelopからmainに変更
          context:
            - BATCH1_DEV
